## 强制指向 24.10.5 官方稳定版仓库
src/gz openwrt_core https://downloads.immortalwrt.org/releases/24.10.5/targets/x86/64/packages
src/gz openwrt_base https://downloads.immortalwrt.org/releases/24.10.5/packages/x86_64/base
src/gz openwrt_luci https://downloads.immortalwrt.org/releases/24.10.5/packages/x86_64/luci
src/gz openwrt_packages https://downloads.immortalwrt.org/releases/24.10.5/packages/x86_64/packages
src/gz openwrt_routing https://downloads.immortalwrt.org/releases/24.10.5/packages/x86_64/routing
src/gz openwrt_telephony https://downloads.immortalwrt.org/releases/24.10.5/packages/x86_64/telephony

src imagebuilder file:packages
option check_signature 0