name: Build OpenWrt x86 Image

on:

env:
  PREFIX_URL: https://downloads.immortalwrt.org/releases/24.10.5/targets/x86/64
  IB_NAME: immortalwrt-imagebuilder-24.10.5-x86-64.Linux-x86_64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev gawk git gettext \
            libssl-dev xsltproc rsync wget unzip python3 qemu-utils zstd genisoimage

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Download and Setup Image Builder
        run: |
          wget -q $PREFIX_URL/$IB_NAME.tar.zst
          tar --zstd -xf $IB_NAME.tar.zst
          cd $IB_NAME
          # 拷贝配置文件与自定义文件
          cp -rf $GITHUB_WORKSPACE/files .
          [ -f files/etc/rc.local ] && chmod +x files/etc/rc.local

     - name: Build RootFS
        run: |
          cd $IB_NAME
          PACKAGES=$(cat $GITHUB_WORKSPACE/config/normal-packages.config | tr -s "\n" " ")
          
          # 核心修正：拼写改为 CONFIG_TARGET_ROOTFS_TARGZ
          make image PACKAGES="$PACKAGES" FILES="$GITHUB_WORKSPACE/files" \
            CONFIG_TARGET_ROOTFS_TARGZ=y \
            CONFIG_TARGET_IMAGES_GZ=n \
            CONFIG_TARGET_IMAGE_ISO=n \
            CONFIG_TARGET_IMAGE_VHDX=n \
            CONFIG_VMDK_IMAGES=n \
            CONFIG_GRUB_IMAGES=n \
            CONFIG_TARGET_IMAGES_PAD=n

          # 现在这个命令就能找到生成的 .tar.gz 文件了
          mv bin/targets/x86/64/*rootfs.tar.gz $GITHUB_WORKSPACE/openwrt-rootfs.tar.gz

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/openwrt:x86_64
            ${{ secrets.DOCKERHUB_USERNAME }}/openwrt:latest
